language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: zHEl4jySO0FAWC6bN76XaQFbnz9FX4wEnuAEetGAgXvs52KUHPkiWwyCZSNrZG0FTUH9n967rWj9i0+ybXK1xZc/Cda9tQflIqYK8UVveuUC/SNU23bPgHvlHEjMp6cwBxJkA6wUo11WbAzoRrHUoHVO4sodi6JFFnrmgxAszplUj6NovcUlAOB3D2/fnNMJpIHV2SUf1zAxm6GAxPknH4v30oPIDbHTQEGQX1TwwUYe2kivO2ZGfYy4IdwbnDvarpba1RftO2gG0lNA89vUkAwN+hbZeMq1sj0qVycB8jclKmUJu8Yi2cnFJyno/h/VtXgpF54rKCycMW0ijmISy4+x5SDvi2zEATVUxg7rI3shnEqwWc7R2Al6FpEpOLcBJO9k/Tt+7Zc1j/AvrPjFWNF7aNLs505K+YS8eg0aAE3ssIeI+pKdTDxJwWO8BuH46yAjzHjsAPmF8aXprxkCdTiQVyQueKNjMvt8oqFOHpFRqh56eZl27C6JHWlTPyeOAVhA4T2b+k0HhssC/f91Vs5bpEHKKAfRrWomCd4Z3BUdMclKSemyOjc/DTZWwsMLQ0jb1f/EkuLKMn1Yz/FpH2HIJdSnHMBEWXy2CRBtNmXo76/zB9sV5MptxR0SoOACwr+ZSbJWqiOWqHOHtQhMC4zecpvznviQd1z9APDi/NA=
  - secure: YcKbzVmieGT6rHVCZ7Z9K+uDmLimhROFWVwWSG9eZj2z2uLbQVBDz8molYfkJP/jKR/wdpb+Nc8ETxxNTUYIwQR7DZEkGvFZhm8AdSLDjkgPoMyvYr6FHpnpRteA+2nadfdEUP2nVzispeDbyH7fEOauee24ssrX5iStWGBRbsbSDduiEp1NTdCkSRMimFXbYogio9zEQxKkDIRfoq7pLsiIYCQdK4gwL9Lp+hu2qdg5DzHwv4ZSfAC8lQQA8XghcXPQUnFNp65YeUP/jAhMy27KSCDCgLpvip4Ag0e0FgH6EMHDHF4R98riw5kWvcK109qOjJ4cZ3v8AWzEezJaY7AvCnw51sMpBJCST4A6+/fRKFJOuqh6uOlXQvzGSgZaRtH81RurbbxI0yub8o0T7eJUNBH3QS3KjCbGdS0FB8uankItvHDApCUM0r957BXAuYWzGgHHYwUHPVZsypxP2/bZtgNSeBnF3K9wHq6BvOAdfCiYAn4ra8CR/syK42EDKsKNN6+Sp+IfMyYJfEUJWAGwg2D9DrMxBPKD/FadBXLoOltyxrFGYNbEySwbnvEsoDSmiPCFwQSixo9aAxXRCAL+Hca52yRCH9WS+Npl67RJ4OQCQYrnF2LnTQ0ZUyXEnlEHyLNp15jh4rYMB2Hr1qQX+XGFjzre5rhhZ3Iyizc=
  - secure: WxFpoGothtR9c3dCZrO7lZQqq6z0aULb2UrxQPDI6rcC0CzwmEDNehxfWV2kHcqftgOsnIbUqeYmkAN/E6KdAh4Z11cwj8P2a6rppp0/ikUq0UsV9shJ0GJu6jom/+Wj8Juhl5FjSUlqRdhR6yElfIo+1K0TRPilxrT9MX2IQmS8O/J7q47Xl14NiBPRLfl/zA9a7vfobQNR4dhWf86whfHrOy9U9BH6+aTJaFfwet+pUU8tggnY6A4430V4HuFOHdS7q322Tn+SRGArnvBBFgRCmEuLC/sI/8WHUcJS1mivR+Odqu+LYGP5tfW3HmxY3KT1KJ1j4o9o9BnagPYema5b8/AsY0bvgJE62qoMlZDbJUmM6O9mJ6EJD3st365L7EaAIX7MR4Y8GrjaMUxozY2mgH1FUNpC3IrnsGBin+6A5YGPfFdqC5feY/cPgzHIF6M/SiuuAUXH+vLsEYuzPiF1zhH+OFWzaqlDqkHADozLJLOFXN/XzO9qKUHqo+NO8oJH3UcCX5oZYTnj3L94YuRRmKIc5N0z9oQqcwpr8GKVVjS5vNAOwZLowSOkrlai3n9WZLYkztB/Cxwwm/cUhuOrVUmMvDt3KBTi4ayx7fDayyAVD0Uvp/mu5+9ocJ6HcSjt3/afq4b2r5kIONAGqC5N04wTappX6ydyDKJGZGc=

script:
- echo 'No test'

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
